# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/damarcocobadocker:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/damarcocobadocker:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/damarcocobadocker:buildcache,mode=max
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Check update
    #   run: |
    #     sudo apt-get update
    # - name: Install library
    #   run: |
    #     sudo apt-get install -y xvfb wget ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcups2 libdbus-1-3 libgbm1 libgtk-3-0 libnspr4 libnss3 libxcomposite1 libxkbcommon0 libxrandr2 xdg-utils ntpdate openssl
    # - name: Install browser
    #   run: |
    #     wget -q https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz \
    #     && tar -xf geckodriver-v0.30.0-linux64.tar.gz \
    #     && rm geckodriver-v0.30.0-linux64.tar.gz \
    #     && mkdir ../driver \
    #     && mkdir ../driver/mac \
    #     && mv geckodriver ../driver/mac/geckodriver \
    #     && sudo chmod +x ../driver/mac/geckodriver
    - name: Test with behave
      run: |
        behave -i features
